/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appSisPlan;

import java.util.List;
import javax.swing.JOptionPane;
import sisPlanBLL.CategoriaEspecialidadesBLL;
import sisPlanBLL.EspecialidadBLL;
import sisPlanEntidades.CategoriaEspecialidades;
import sisPlanEntidades.Especialidad;

/**
 *
 * @author Daniela Fabiola
 */
public class jDlgMantenimientoEspecialidades extends javax.swing.JDialog {
    EspecialidadBLL accionEspecialidadBLL=new EspecialidadBLL();
    /**
     * Creates new form jDlgMantenimientoEspecialidades
     */
    public jDlgMantenimientoEspecialidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCategoria();
    }
 /**
 * Carga las categorías de especialidades en un JComboBox.
 */   
    public void cargarCategoria(){
        CategoriaEspecialidadesBLL categoriaEspecialidadesBLL = new CategoriaEspecialidadesBLL();
        List<CategoriaEspecialidades> categoria = categoriaEspecialidadesBLL.getListaCategoriaEspecialidades();

        for (CategoriaEspecialidades item : categoria) {
            jCboCategoriaEspecialidades.addItem(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBotEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBotModificar = new javax.swing.JButton();
        jBotAgregar = new javax.swing.JButton();
        jCboCategoriaEspecialidades = new javax.swing.JComboBox<>();
        jTxtDescripcion = new javax.swing.JTextField();
        jBotConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Categoría Especialidad");

        jBotEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jBotEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Eliminar.png"))); // NOI18N
        jBotEliminar.setText("Eliminar");
        jBotEliminar.setFocusable(false);
        jBotEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotEliminar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotEliminar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotEliminar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotEliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Descripción");

        jBotModificar.setBackground(new java.awt.Color(255, 255, 255));
        jBotModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Modificar.png"))); // NOI18N
        jBotModificar.setText("Modificar");
        jBotModificar.setFocusable(false);
        jBotModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotModificar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotModificar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotModificar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotModificarActionPerformed(evt);
            }
        });

        jBotAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jBotAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Nuevo.png"))); // NOI18N
        jBotAgregar.setText("Agregar");
        jBotAgregar.setFocusable(false);
        jBotAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotAgregar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotAgregar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotAgregar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotAgregarActionPerformed(evt);
            }
        });

        jCboCategoriaEspecialidades.setEditable(true);
        jCboCategoriaEspecialidades.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTxtDescripcion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jBotConsultar.setBackground(new java.awt.Color(255, 255, 255));
        jBotConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Consultar.png"))); // NOI18N
        jBotConsultar.setText("Consultar");
        jBotConsultar.setFocusable(false);
        jBotConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotConsultar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotConsultar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotConsultar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addComponent(jCboCategoriaEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBotConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(jBotAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jBotModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jBotEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBotConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jBotAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboCategoriaEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotEliminarActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(option>1){
            Especialidad mEspecialidad= accionEspecialidadBLL.buscarEspecialidadPorNombre(jTxtDescripcion.getText());
        
        if(mEspecialidad!=null){
        accionEspecialidadBLL.eliminarEspecialidad(String.valueOf(mEspecialidad.getEspecialidadID()));
        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
        }
    }//GEN-LAST:event_jBotEliminarActionPerformed

    private void jBotModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotModificarActionPerformed
        Especialidad mEspecialidad= accionEspecialidadBLL.buscarEspecialidadPorNombre(jTxtDescripcion.getText());
        if(mEspecialidad!=null){
        Especialidad especialidad= new Especialidad(mEspecialidad.getEspecialidadID(), ((CategoriaEspecialidades)jCboCategoriaEspecialidades.getSelectedItem()).getIdCategoria(), jTxtDescripcion.getText());
        accionEspecialidadBLL.modificarEspecialidad(especialidad);
        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
    }//GEN-LAST:event_jBotModificarActionPerformed

    private void jBotAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotAgregarActionPerformed
       if(accionEspecialidadBLL.consecutivo()>0&& ((CategoriaEspecialidades)jCboCategoriaEspecialidades.getSelectedItem()).getIdCategoria()>0&&!jTxtDescripcion.getText().isEmpty()){
        Especialidad especialidad= new Especialidad(accionEspecialidadBLL.consecutivo(), ((CategoriaEspecialidades)jCboCategoriaEspecialidades.getSelectedItem()).getIdCategoria(), jTxtDescripcion.getText());
        accionEspecialidadBLL.agregarEspecialidad(especialidad);
       }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
    }//GEN-LAST:event_jBotAgregarActionPerformed

    private void jBotConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotConsultarActionPerformed
        String descripcion=jTxtDescripcion.getText();
        Especialidad mEspecialidad= accionEspecialidadBLL.buscarEspecialidadPorNombre(descripcion);
        CategoriaEspecialidadesBLL categoriaEspecialidadesBLL = new CategoriaEspecialidadesBLL();
        if(mEspecialidad!=null){
            CategoriaEspecialidades categoria=categoriaEspecialidadesBLL.buscarCategoriaEspecialidades(mEspecialidad.getCategoriaEspecialidades());
            jCboCategoriaEspecialidades.setSelectedItem(categoria);
        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
    }//GEN-LAST:event_jBotConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoEspecialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoEspecialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoEspecialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoEspecialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlgMantenimientoEspecialidades dialog = new jDlgMantenimientoEspecialidades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotAgregar;
    private javax.swing.JButton jBotConsultar;
    private javax.swing.JButton jBotEliminar;
    private javax.swing.JButton jBotModificar;
    private javax.swing.JComboBox<CategoriaEspecialidades> jCboCategoriaEspecialidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtDescripcion;
    // End of variables declaration//GEN-END:variables
}
