/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appSisPlan;

import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sisPlanBLL.ExpedienteMedicoBLL;
import sisPlanBLL.PacienteBLL;
import sisPlanBLL.RegistroPadecimientoBLL;
import sisPlanEntidades.Paciente;
import sisPlanEntidades.RegistroPadecimiento;
import sisPlanUtilitario.UtilitarioVentana;
import sisPlanUtilitario.Pila;

/**
 *
 * @author Daniela Fabiola
 */
public class jDlgHistorialMedico extends javax.swing.JDialog {

   PacienteBLL accionPaciente= new PacienteBLL();
   private DefaultTableModel oModeloTablaDatos;
   ExpedienteMedicoBLL expediente= new ExpedienteMedicoBLL();
   RegistroPadecimientoBLL registro= new RegistroPadecimientoBLL();
   String numExpediente;
 
    public jDlgHistorialMedico(java.awt.Frame parent, boolean modal) throws ParseException {
        initComponents();
        inicializarJTable();
        jBtoGroup.add(this.jRdoBotFemenino);
        jBtoGroup.add(this.jRdoBotMasculino);
        numExpediente= jTxtNoExpediente.getText();
    }
/**
 * Inicializa la tabla con los títulos de las columnas y permite seleccionar filas completas.
 */    
    private void inicializarJTable(){
        //Cuando se marca cualquier celda 
        //hace que se marque la fila completa
        jTable.setRowSelectionAllowed(true);
        
        //Aplicar el DefaultTableModel a la Tabla de Datos        
        String[] arregloTitulosTabla = {"Padecimiento", "Tratamiento Fármaceutico", "Servicio Médico", "Médico Tratante"};
        oModeloTablaDatos = new DefaultTableModel(arregloTitulosTabla, 0);
        jTable.setModel(oModeloTablaDatos);
    }
/**
 * Carga los datos en la tabla de registros de padecimientos para un paciente.
 */
    private void cargarJTable() throws ParseException {        
        //Definir objeto Vector para cargar datos
        String[] vDatosTabla = new String[4];
        
        //Limpiar los rows
        this.oModeloTablaDatos.setRowCount(0);
        Paciente paciente=accionPaciente.buscarPaciente(this.jTxtCedula.getText()); 
        //Obtener la lista de RegistroPadecimientos del BLL
        List<RegistroPadecimiento> listaRegistroPadecimientos = registro.getListaRegistroPadecimientos(String.valueOf(expediente.buscarExpedienteMedicoPorCedula(paciente.getCedula()).getNumExpediente()));
       
            for (RegistroPadecimiento oRegistroPadecimiento : listaRegistroPadecimientos) {
                String producto="";
                String servicio="";
                String enfermedad="";
                if(oRegistroPadecimiento.getProducto()!=null){
                    producto=oRegistroPadecimiento.getProducto().toString();
                }
                if(oRegistroPadecimiento.getServiciosMedicos()!=null){
                    servicio=oRegistroPadecimiento.getServiciosMedicos().toString();
                }
                if(oRegistroPadecimiento.getEnfermedad()!=null){
                    enfermedad=oRegistroPadecimiento.getEnfermedad().toString();
                }
                //Leer los datos del objeto que se esta iterando
                vDatosTabla[0] = enfermedad;
                vDatosTabla[1] = producto;
                vDatosTabla[2] = servicio;
                vDatosTabla[3] = oRegistroPadecimiento.getDoctor().toString();
                
                //Agregar la instancia al objeto modelo
                oModeloTablaDatos.addRow(vDatosTabla);
            }
            jTable.setModel(oModeloTablaDatos);     
    }
 /**
 * Obtiene el número de expediente desde un campo de texto.
 */ 
    public String getNumExpediente() {
        return this.numExpediente = jTxtNoExpediente.getText();
    }
     
    private void cargarVentana() throws ParseException{
        JDlgPadecimiento oJDlgPadecimiento = new JDlgPadecimiento(null, true);
        UtilitarioVentana.centrarVentanaJDialog(oJDlgPadecimiento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtoGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNombrePaciente = new javax.swing.JTextField();
        jTxtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRdoBotFemenino = new javax.swing.JRadioButton();
        jRdoBotMasculino = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtNoExpediente = new javax.swing.JTextField();
        jBotNuevoRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Nombre y Apellidos");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Número de Cédula");

        jTxtNombrePaciente.setEditable(false);
        jTxtNombrePaciente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTxtCedula.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCedulaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Edad");

        jTxtEdad.setEditable(false);
        jTxtEdad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Género");

        jRdoBotFemenino.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jRdoBotFemenino.setText("F");

        jRdoBotMasculino.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jRdoBotMasculino.setText("M");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("No. Expediente");

        jTxtNoExpediente.setEditable(false);
        jTxtNoExpediente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jBotNuevoRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBotNuevoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/anadir.png"))); // NOI18N
        jBotNuevoRegistro.setText("Nuevo Registro");
        jBotNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotNuevoRegistroActionPerformed(evt);
            }
        });

        jTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.setGridColor(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(jTable);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/actualizar_1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/salida.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/agregar.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtCedula)
                                    .addComponent(jTxtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRdoBotFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(jRdoBotMasculino))
                            .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jBotNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtNoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jRdoBotMasculino))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jRdoBotFemenino))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtNoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jBotNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCedulaActionPerformed
        jTxtNoExpediente.setText("");
        if(jTxtCedula.getText().length()==9){
            if(accionPaciente.buscarPaciente(jTxtCedula.getText())!=null){

                Paciente paciente=accionPaciente.buscarPaciente(this.jTxtCedula.getText());
                jTxtNombrePaciente.setText(paciente.getNombreApellidos());
                jTxtEdad.setText(String.valueOf(paciente.edad()));
                
                try {
                    if(expediente.buscarExpedienteMedicoPorCedula(paciente.getCedula())!=null){
                        try {
                            numExpediente=String.valueOf(expediente.buscarExpedienteMedicoPorCedula(paciente.getCedula()).getNumExpediente());
                            jTxtNoExpediente.setText(numExpediente);
                        } catch (ParseException ex) {
                            Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if(paciente.getGenero()=='F'){
                            jRdoBotFemenino.setSelected(true);
                        }else{
                            jRdoBotMasculino.setSelected(true);
                        }
                        try {
                            cargarJTable();
                        } catch (ParseException ex) {
                            Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Genere un expediente");
                    }   } catch (ParseException ex) {
                    Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Persona no existe");
            }

        }
    }//GEN-LAST:event_jTxtCedulaActionPerformed

    private void jBotNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotNuevoRegistroActionPerformed
        if(jTxtNoExpediente.getText().length()>0){
            try {
                 Pila.agregarElemento(jTxtNoExpediente.getText());
                cargarVentana();
            } catch (ParseException ex) {
                Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No hay expediente asociado, genere uno en paciente");
        }
    }//GEN-LAST:event_jBotNuevoRegistroActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(jTxtCedula.getText().length()==9){
            if(accionPaciente.buscarPaciente(jTxtCedula.getText())!=null){

                Paciente paciente=accionPaciente.buscarPaciente(this.jTxtCedula.getText());
                jTxtNombrePaciente.setText(paciente.getNombreApellidos());
                jTxtEdad.setText(String.valueOf(paciente.edad()));
                try {
                    numExpediente=String.valueOf(expediente.buscarExpedienteMedicoPorCedula(paciente.getCedula()).getNumExpediente());
                    jTxtNoExpediente.setText(numExpediente);
                } catch (ParseException ex) {
                    Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(paciente.getGenero()=='F'){
                    jRdoBotFemenino.setSelected(true);
                }else{
                    jRdoBotMasculino.setSelected(true);
                }
                try {
                    cargarJTable();
                } catch (ParseException ex) {
                    Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else{
                JOptionPane.showMessageDialog(null, "Persona no existe");
            }

        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        dispose();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        JDlgCrearExpediente crear = null;
        try {
            crear = new JDlgCrearExpediente(null, true);
        } catch (ParseException ex) {
            Logger.getLogger(JFrmPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
       UtilitarioVentana.centrarVentanaJDialog(crear);
    }//GEN-LAST:event_jLabel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlgHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlgHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlgHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlgHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlgHistorialMedico dialog = null;
                try {
                    dialog = new jDlgHistorialMedico(new javax.swing.JFrame(), true);
                } catch (ParseException ex) {
                    Logger.getLogger(jDlgHistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotNuevoRegistro;
    private javax.swing.ButtonGroup jBtoGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRdoBotFemenino;
    private javax.swing.JRadioButton jRdoBotMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtCedula;
    private javax.swing.JTextField jTxtEdad;
    private javax.swing.JTextField jTxtNoExpediente;
    private javax.swing.JTextField jTxtNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
