/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appSisPlan;

import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import sisPlanBLL.DoctorBLL;
import sisPlanEntidades.Doctor;

/**
 *
 * @author Daniela Fabiola
 */
public class jDlgHoraAlmuerzo extends javax.swing.JDialog {
    
    /**
     * Creates new form jDlgHoraAlmuerzo
     */
    public jDlgHoraAlmuerzo(java.awt.Frame parent, boolean modal) throws ParseException {
        super(parent, modal);
        initComponents();
        cargarHora();
        cargarDoctores();
    }
    
    private void cargarHora(){
        jCboHora.addItem("12:00md - 1:00pm");
        jCboHora.addItem("1:00pm - 2:00pm");
        
    }
    
    private void cargarDoctores() throws ParseException{
        
        //DefaultListModel<String> representa una lista de elementos se utiliza para mostrar datos en componentes de interfaz de usuario como JList.
        DoctorBLL Doctor= new DoctorBLL();
        List<Doctor> listaDoctores = Doctor.getListaDoctors();
        DefaultListModel<Doctor> modeloDoctor = new DefaultListModel<>();

        for (Doctor Doctor1 : listaDoctores) {
            modeloDoctor.addElement(Doctor1);
        }

        JList<Doctor> jLstDoctores= new JList<>(modeloDoctor);
        this.jLstDoctores.setModel(jLstDoctores.getModel());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLstDoctores = new javax.swing.JList<>();
        jCboHora = new javax.swing.JComboBox<>();
        jTxtCodigoColegiado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLstDoctores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jLstDoctores);

        jCboHora.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCboHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboHoraActionPerformed(evt);
            }
        });

        jTxtCodigoColegiado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxtCodigoColegiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoColegiadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Número Colegiado");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Hora");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/actualizar_1.png"))); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigoColegiado, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCodigoColegiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboHoraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DoctorBLL accionDoctor= new DoctorBLL();
       
            if(accionDoctor.buscarDoctor(String.valueOf(jLstDoctores.getSelectedValue().getNumColegiado()))!=null){
                Doctor Doctor=accionDoctor.buscarDoctor(String.valueOf(jLstDoctores.getSelectedValue().getNumColegiado())); 
                Doctor doctor= new Doctor(Doctor.getNumColegiado(), Doctor.getCedula(), Doctor.getNombreApellidos(), Doctor.getFechaNacimiento(), Doctor.getGenero(), Doctor.getTelefonoCelular(), Doctor.getTelefonoCasa(), Doctor.getTelefonoOficina(), Doctor.getProvincia(), Doctor.getCanton(), Doctor.getDistrito(), Doctor.getSennas(), Doctor.getEspecialidad(),(String)jCboHora.getSelectedItem());             
                
                accionDoctor.modificarDoctor(doctor);
            }else{
                JOptionPane.showMessageDialog(null, "No existe");
            }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtCodigoColegiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoColegiadoActionPerformed
        DoctorBLL doctorBLL = new DoctorBLL();
        String numColegiadoBuscado = jTxtCodigoColegiado.getText();
        int indexDoctor = -1;

        if (numColegiadoBuscado != null && !numColegiadoBuscado.isEmpty()) {
            DefaultListModel<Doctor> model = (DefaultListModel<Doctor>) jLstDoctores.getModel();
            int size = model.getSize();

            for (int i = 0; i < size; i++) {
                Doctor doctorEnLista = model.getElementAt(i);
                if (String.valueOf(doctorEnLista.getNumColegiado()).equals(numColegiadoBuscado)) {
                    indexDoctor = i;
                    break;
                }
            }

            if (indexDoctor != -1) {
                jLstDoctores.setSelectedIndex(indexDoctor);
                jLstDoctores.ensureIndexIsVisible(indexDoctor);
            }
        } else{
                JOptionPane.showMessageDialog(null, "No existe");
            }
    }//GEN-LAST:event_jTxtCodigoColegiadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlgHoraAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlgHoraAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlgHoraAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlgHoraAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlgHoraAlmuerzo dialog = null;
                try {
                    dialog = new jDlgHoraAlmuerzo(new javax.swing.JFrame(), true);
                } catch (ParseException ex) {
                    Logger.getLogger(jDlgHoraAlmuerzo.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCboHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Doctor> jLstDoctores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCodigoColegiado;
    // End of variables declaration//GEN-END:variables
}
