/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appSisPlan;

import java.util.List;
import javax.swing.JOptionPane;
import sisPlanBLL.CategoriaServicioMedicoBLL;
import sisPlanBLL.ServiciosMedicosBLL;
import sisPlanEntidades.CategoriaServicioMedico;
import sisPlanEntidades.ServiciosMedicos;
import sisPlanUtilitario.ValidadorFormatos;

/**
 *
 * @author Daniela Fabiola
 */
public class jDlgMantenimientoServiciosMedicos extends javax.swing.JDialog {
    ServiciosMedicosBLL accionServicio=new ServiciosMedicosBLL();
    /**
     * Creates new form jDlgMantenimientoServiciosMedicos
     */
    public jDlgMantenimientoServiciosMedicos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarServicioCategoria();
    }
    
    /**
    * Carga las categorías de servicio médico en un JComboBox.
    */
   public void cargarServicioCategoria() {
       // Crear una instancia del BLL para manejar las categorías de servicio médico
       CategoriaServicioMedicoBLL categoriaServicioMedicoBLL = new CategoriaServicioMedicoBLL();

       // Obtener la lista de categorías de servicio médico
       List<CategoriaServicioMedico> listaCategoria = categoriaServicioMedicoBLL.getListaCategoriaServicioMedico();

       // Agregar cada categoría de servicio médico al JComboBox
       for (CategoriaServicioMedico categoria : listaCategoria) {
           jCboCategoriaServiciosMedicos.addItem(categoria);
       }
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotConsultar = new javax.swing.JButton();
        jBotEliminar = new javax.swing.JButton();
        jBotModificar = new javax.swing.JButton();
        jBotAgregar = new javax.swing.JButton();
        jCboCategoriaServiciosMedicos = new javax.swing.JComboBox<>();
        jTxtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFactorCosto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jBotConsultar.setBackground(new java.awt.Color(255, 255, 255));
        jBotConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Consultar.png"))); // NOI18N
        jBotConsultar.setText("Consultar");
        jBotConsultar.setFocusable(false);
        jBotConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotConsultar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotConsultar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotConsultar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotConsultarActionPerformed(evt);
            }
        });

        jBotEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jBotEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Eliminar.png"))); // NOI18N
        jBotEliminar.setText("Eliminar");
        jBotEliminar.setFocusable(false);
        jBotEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotEliminar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotEliminar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotEliminar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotEliminarActionPerformed(evt);
            }
        });

        jBotModificar.setBackground(new java.awt.Color(255, 255, 255));
        jBotModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Modificar.png"))); // NOI18N
        jBotModificar.setText("Modificar");
        jBotModificar.setFocusable(false);
        jBotModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotModificar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotModificar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotModificar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotModificarActionPerformed(evt);
            }
        });

        jBotAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jBotAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Nuevo.png"))); // NOI18N
        jBotAgregar.setText("Agregar");
        jBotAgregar.setFocusable(false);
        jBotAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotAgregar.setMaximumSize(new java.awt.Dimension(70, 60));
        jBotAgregar.setMinimumSize(new java.awt.Dimension(70, 60));
        jBotAgregar.setPreferredSize(new java.awt.Dimension(70, 60));
        jBotAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotAgregarActionPerformed(evt);
            }
        });

        jCboCategoriaServiciosMedicos.setEditable(true);
        jCboCategoriaServiciosMedicos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTxtDescripcion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Categoria Servicio Médico");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Descripción");

        jTxtFactorCosto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Factor Costo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFactorCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBotConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jBotAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCboCategoriaServiciosMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jBotModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBotEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBotConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jBotAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboCategoriaServiciosMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFactorCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotConsultarActionPerformed
        CategoriaServicioMedicoBLL categoria= new CategoriaServicioMedicoBLL();
        ServiciosMedicos mServiciosMedicos=accionServicio.buscarServiciosMedicosPorNombre(jTxtDescripcion.getText());
        
        if(mServiciosMedicos!=null){
            jCboCategoriaServiciosMedicos.setSelectedItem(categoria.buscarCategoriaServicioMedico(mServiciosMedicos.getCategoriaServiciosMedicos()));
            jTxtFactorCosto.setText(String.valueOf(mServiciosMedicos.getFactorCosto()));
        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
            
    }//GEN-LAST:event_jBotConsultarActionPerformed

    private void jBotEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotEliminarActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(option>1){
            ServiciosMedicos mServiciosMedicos=accionServicio.buscarServiciosMedicosPorNombre(jTxtDescripcion.getText());
             if(mServiciosMedicos!=null){
                 accionServicio.eliminarServiciosMedicos(String.valueOf(mServiciosMedicos.getIdServicio()));
             }
        }
    }//GEN-LAST:event_jBotEliminarActionPerformed

    private void jBotModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotModificarActionPerformed
        ServiciosMedicos mServiciosMedicos=accionServicio.buscarServiciosMedicosPorNombre(jTxtDescripcion.getText());
        if(ValidadorFormatos.validarDouble(jTxtFactorCosto.getText())){
            if(mServiciosMedicos!=null){
                ServiciosMedicos serviciosMedicos=new ServiciosMedicos(mServiciosMedicos.getIdServicio(), jTxtDescripcion.getText(), 
                                               Double.parseDouble(jTxtFactorCosto.getText()), ((CategoriaServicioMedico)jCboCategoriaServiciosMedicos.getSelectedItem()).getIdCategoria());
                accionServicio.modificarServiciosMedicos(serviciosMedicos);
           }else{
               JOptionPane.showMessageDialog(null, "Faltan Datos");
           }
        }else{
            JOptionPane.showMessageDialog(null, "Factor Costo mal escrito");
        }
    }//GEN-LAST:event_jBotModificarActionPerformed

    private void jBotAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotAgregarActionPerformed

        if(ValidadorFormatos.validarDouble(jTxtFactorCosto.getText())){
            int consecutivo=accionServicio.consecutivo();
            String nombre=jTxtDescripcion.getText();
            double factor= Double.parseDouble(jTxtFactorCosto.getText());
            int cat= ((CategoriaServicioMedico)jCboCategoriaServiciosMedicos.getSelectedItem()).getIdCategoria();
            if(!nombre.isEmpty()&&factor>-1&&cat>-1&&consecutivo>0){
            ServiciosMedicos serviciosMedicos=new ServiciosMedicos(consecutivo, nombre, 
                                              factor , cat);
            accionServicio.agregarServiciosMedicos(serviciosMedicos);
            }else{
                JOptionPane.showMessageDialog(null, "Faltan Datos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Factor Costo mal escrito");
        }
    }//GEN-LAST:event_jBotAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoServiciosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoServiciosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoServiciosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlgMantenimientoServiciosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlgMantenimientoServiciosMedicos dialog = new jDlgMantenimientoServiciosMedicos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotAgregar;
    private javax.swing.JButton jBotConsultar;
    private javax.swing.JButton jBotEliminar;
    private javax.swing.JButton jBotModificar;
    private javax.swing.JComboBox<CategoriaServicioMedico> jCboCategoriaServiciosMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTxtDescripcion;
    private javax.swing.JTextField jTxtFactorCosto;
    // End of variables declaration//GEN-END:variables
}
