/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appSisPlan;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import sisPlanUtilitario.UtilitarioVentana;

/**
 *
 * @author Daniela Fabiola
 */
public class jFrmMantenimientos extends javax.swing.JFrame {

    /**
     * Creates new form jFrmMantenimientos
     */
    public jFrmMantenimientos() {
        initComponents();
         setSize(1800, 1000);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuInicio = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuEspecialidad = new javax.swing.JMenuItem();
        jMnuProducto = new javax.swing.JMenuItem();
        jMnuServicios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jMnuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/pagina-de-inicio.png"))); // NOI18N
        jMnuInicio.setText("Inicio");
        jMnuInicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMnuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMnuInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(jMnuInicio);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/rueda-dentada.png"))); // NOI18N
        jMenu2.setText("Mantenimientos");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenuUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/agregar-usuario.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuUsuario);

        jMenuEspecialidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/estetoscopio (2).png"))); // NOI18N
        jMenuEspecialidad.setText("Especialidad");
        jMenuEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEspecialidadActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuEspecialidad);

        jMnuProducto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMnuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/pastillas.png"))); // NOI18N
        jMnuProducto.setText("Productos Farmacéuticos");
        jMnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuProducto);

        jMnuServicios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMnuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/servicios-medicos.png"))); // NOI18N
        jMnuServicios.setText("Servicios Médicos");
        jMnuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuServiciosActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuServicios);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        jDlgMantenimientoUsuario user = null;
        user= new jDlgMantenimientoUsuario(null, true);
       UtilitarioVentana.centrarVentanaJDialog(user);
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEspecialidadActionPerformed
        jDlgMantenimientoEspecialidades mant = null;
        mant= new jDlgMantenimientoEspecialidades(null, true);
       UtilitarioVentana.centrarVentanaJDialog(mant);
    }//GEN-LAST:event_jMenuEspecialidadActionPerformed

    private void jMnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProductoActionPerformed
         jDlgMantenimientoProductosFarmaceuticos mant = null;
        mant= new jDlgMantenimientoProductosFarmaceuticos(null, true);
       UtilitarioVentana.centrarVentanaJDialog(mant);
    }//GEN-LAST:event_jMnuProductoActionPerformed

    private void jMnuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuServiciosActionPerformed
        jDlgMantenimientoServiciosMedicos mant = null;
        mant= new jDlgMantenimientoServiciosMedicos(null, true);
       UtilitarioVentana.centrarVentanaJDialog(mant);
    }//GEN-LAST:event_jMnuServiciosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      jFrmMenuPrincipal menu=new jFrmMenuPrincipal();
      menu.setVisible(true);
      System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jMnuInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMnuInicioMousePressed
        jFrmMenuPrincipal menu=new jFrmMenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMnuInicioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmMantenimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEspecialidad;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JMenu jMnuInicio;
    private javax.swing.JMenuItem jMnuProducto;
    private javax.swing.JMenuItem jMnuServicios;
    // End of variables declaration//GEN-END:variables
}
