
package appSisPlan;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sisPlanUtilitario.UtilitarioVentana;
/**
 *
 * @author Daniela Fabiola
 */
public class JFrmPersonas extends javax.swing.JFrame {

    public JFrmPersonas() {
        initComponents();
        setSize(1800, 1000);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDepAdministradorEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenPaciente = new javax.swing.JMenu();
        jMenuIRegistrarPaciente = new javax.swing.JMenuItem();
        jMIActualizarPaciente = new javax.swing.JMenuItem();
        jMIEliminarPaciente = new javax.swing.JMenuItem();
        jMenDoctor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenIActualizarDoctor = new javax.swing.JMenuItem();
        jMenIEliminarDoctor = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jCrearExpediente = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDepAdministradorEscritorio.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jDepAdministradorEscritorioComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jDepAdministradorEscritorioLayout = new javax.swing.GroupLayout(jDepAdministradorEscritorio);
        jDepAdministradorEscritorio.setLayout(jDepAdministradorEscritorioLayout);
        jDepAdministradorEscritorioLayout.setHorizontalGroup(
            jDepAdministradorEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1181, Short.MAX_VALUE)
        );
        jDepAdministradorEscritorioLayout.setVerticalGroup(
            jDepAdministradorEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jMenuBar1ComponentResized(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/pagina-de-inicio.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/paciente.png"))); // NOI18N
        jMenPaciente.setText("Paciente");
        jMenPaciente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenuIRegistrarPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuIRegistrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/agregar-usuario.png"))); // NOI18N
        jMenuIRegistrarPaciente.setText("Registrar Paciente");
        jMenuIRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIRegistrarPacienteActionPerformed(evt);
            }
        });
        jMenPaciente.add(jMenuIRegistrarPaciente);

        jMIActualizarPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMIActualizarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/actualizar (2).png"))); // NOI18N
        jMIActualizarPaciente.setText("Actualizar Paciente");
        jMIActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIActualizarPacienteActionPerformed(evt);
            }
        });
        jMenPaciente.add(jMIActualizarPaciente);

        jMIEliminarPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMIEliminarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/basura.png"))); // NOI18N
        jMIEliminarPaciente.setText("Eliminar Paciente");
        jMIEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEliminarPacienteActionPerformed(evt);
            }
        });
        jMenPaciente.add(jMIEliminarPaciente);

        jMenuBar1.add(jMenPaciente);

        jMenDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/estetoscopio (2).png"))); // NOI18N
        jMenDoctor.setText("Doctor");
        jMenDoctor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/agregar-usuario.png"))); // NOI18N
        jMenuItem3.setText("Registrar Doctor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenDoctor.add(jMenuItem3);

        jMenIActualizarDoctor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenIActualizarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/actualizar (2).png"))); // NOI18N
        jMenIActualizarDoctor.setText("Actualizar Doctor");
        jMenIActualizarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenIActualizarDoctorActionPerformed(evt);
            }
        });
        jMenDoctor.add(jMenIActualizarDoctor);

        jMenIEliminarDoctor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenIEliminarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/basura.png"))); // NOI18N
        jMenIEliminarDoctor.setText("Eliminar Doctor");
        jMenIEliminarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenIEliminarDoctorActionPerformed(evt);
            }
        });
        jMenDoctor.add(jMenIEliminarDoctor);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/editar (2).png"))); // NOI18N
        jMenuItem4.setText("Editar Hora Almuerzo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenDoctor.add(jMenuItem4);

        jMenuBar1.add(jMenDoctor);

        jCrearExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/agregar-documento.png"))); // NOI18N
        jCrearExpediente.setText("Crear Expediente");
        jCrearExpediente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCrearExpediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCrearExpedienteMousePressed(evt);
            }
        });
        jCrearExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearExpedienteActionPerformed(evt);
            }
        });
        jMenuBar1.add(jCrearExpediente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDepAdministradorEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDepAdministradorEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMIActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIActualizarPacienteActionPerformed
        JPanActualizarPaciente oJPanActualizarPaciente = new JPanActualizarPaciente();
        oJPanActualizarPaciente.setVisible(true);
        UtilitarioVentana.centrarVentanaJPanel(this, "Actualizar Paciente",oJPanActualizarPaciente, this.jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMIActualizarPacienteActionPerformed

    private void jMenuIRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIRegistrarPacienteActionPerformed
        JPanRegistrarPaciente oJPanRegistrarPaciente = new JPanRegistrarPaciente();
        oJPanRegistrarPaciente.setVisible(true);
        UtilitarioVentana.centrarVentanaJPanel(this, "Registrar Paciente",oJPanRegistrarPaciente, this.jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMenuIRegistrarPacienteActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
     this.jDepAdministradorEscritorio.setSize(this.getSize() );
    }//GEN-LAST:event_formComponentResized

    private void jDepAdministradorEscritorioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDepAdministradorEscritorioComponentResized
        this.jDepAdministradorEscritorio.setSize(this.getSize() );
    }//GEN-LAST:event_jDepAdministradorEscritorioComponentResized

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jFrmMenuPrincipal menu=new jFrmMenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jMenIEliminarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenIEliminarDoctorActionPerformed
        JPanEliminarDoctor oJPanEliminarDoctor = new JPanEliminarDoctor();
        oJPanEliminarDoctor.setVisible(true);
        UtilitarioVentana.centrarVentanaJPanel(this, "Eliminar Doctor",oJPanEliminarDoctor, this.jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMenIEliminarDoctorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JPanRegistrarDoctor oJPanRegistrarDoctor  = new JPanRegistrarDoctor();
        oJPanRegistrarDoctor .setVisible(true);
        UtilitarioVentana.centrarVentanaJPanel(this, "Registrar Doctor",oJPanRegistrarDoctor , this.jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenIActualizarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenIActualizarDoctorActionPerformed
        JPanActualizarDoctor oJPanActualizarDoctor  = new JPanActualizarDoctor ();
        oJPanActualizarDoctor .setVisible(true);
        UtilitarioVentana.centrarVentanaJPanel(this, "Actualizar Doctor",oJPanActualizarDoctor , this.jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMenIActualizarDoctorActionPerformed

    private void jMenuBar1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1ComponentResized

    private void jMIEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEliminarPacienteActionPerformed
       JPanEliminarPaciente oJPanEliminarPaciente = new JPanEliminarPaciente();
       oJPanEliminarPaciente.setVisible(true);
       UtilitarioVentana.centrarVentanaJPanel(this, "Eliminar Paciente",oJPanEliminarPaciente, this.jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMIEliminarPacienteActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       jFrmMenuPrincipal menu=new jFrmMenuPrincipal();
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jCrearExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearExpedienteActionPerformed
       JDlgCrearExpediente crear = null;
        try {
            crear = new JDlgCrearExpediente(null, true);
        } catch (ParseException ex) {
            Logger.getLogger(JFrmPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
       UtilitarioVentana.centrarVentanaJDialog(crear);
    }//GEN-LAST:event_jCrearExpedienteActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        jFrmMenuPrincipal menu=new jFrmMenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jCrearExpedienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCrearExpedienteMousePressed
        JDlgCrearExpediente crear = null;
        try {
            crear = new JDlgCrearExpediente(null, true);
        } catch (ParseException ex) {
            Logger.getLogger(JFrmPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
       UtilitarioVentana.centrarVentanaJDialog(crear);
    }//GEN-LAST:event_jCrearExpedienteMousePressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jDlgHoraAlmuerzo almuerzo = null;
        try {
            almuerzo = new jDlgHoraAlmuerzo(null, true);
        } catch (ParseException ex) {
            Logger.getLogger(JFrmPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
       UtilitarioVentana.centrarVentanaJDialog(almuerzo );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPersonas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCrearExpediente;
    private javax.swing.JDesktopPane jDepAdministradorEscritorio;
    private javax.swing.JMenuItem jMIActualizarPaciente;
    private javax.swing.JMenuItem jMIEliminarPaciente;
    private javax.swing.JMenu jMenDoctor;
    private javax.swing.JMenuItem jMenIActualizarDoctor;
    private javax.swing.JMenuItem jMenIEliminarDoctor;
    private javax.swing.JMenu jMenPaciente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuIRegistrarPaciente;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
